version: '3'

services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}
    networks:
      - default
      - traefik_proxy
    ports:
      - '80:80'
      - '443:443'
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=traefik'
      - 'traefik.frontend.rule=Host:traefik.${DOMAINNAME}'
      - 'traefik.port=8080'
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.frontend.headers.SSLRedirect=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.browserXSSFilter=true'
      - 'traefik.frontend.headers.contentTypeNosniff=true'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - 'traefik.frontend.headers.SSLHost=replace_me'
      - 'traefik.frontend.headers.STSIncludeSubdomains=true'
      - 'traefik.frontend.headers.STSPreload=true'
      - 'traefik.frontend.headers.frameDeny=true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/a/docker/traefik:/etc/traefik
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/a/docker/portainer/data:/data
    networks:
      - traefik_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=portainer'
      - 'traefik.frontend.rule=Host:portainer.${DOMAINNAME}'
      - 'traefik.port=9000'
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.frontend.headers.SSLRedirect=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.browserXSSFilter=true'
      - 'traefik.frontend.headers.contentTypeNosniff=true'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - 'traefik.frontend.headers.SSLHost=replace_me'
      - 'traefik.frontend.headers.STSIncludeSubdomains=true'
      - 'traefik.frontend.headers.STSPreload=true'
      - 'traefik.frontend.headers.frameDeny=true'
  wetty:
    image: freeflyer/wetty
    container_name: wetty
    restart: always
    environment:
      - WETTY_USER=replace_me
      - WETTY_HASH=replace_me
    networks:
      - traefik_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=wetty'
      - 'traefik.frontend.rule=Host:wetty.${DOMAINNAME}'
      - 'traefik.port=3000'
      - 'traefik.docker.network=traefik_proxy'
      - 'traefik.frontend.headers.SSLRedirect=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.browserXSSFilter=true'
      - 'traefik.frontend.headers.contentTypeNosniff=true'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - 'traefik.frontend.headers.SSLHost=replace_me'
      - 'traefik.frontend.headers.STSIncludeSubdomains=true'
      - 'traefik.frontend.headers.STSPreload=true'
      - 'traefik.frontend.headers.frameDeny=true'
  watchtower:
    container_name: watchtower
    hostname: watchtower
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
